---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Install requirements
  ansible.builtin.include_tasks:
    file: 'requirements.yml'

- name: Create config
  ansible.builtin.include_tasks:
    file: 'configure.yml'
