---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true

- name: Install apt-mirror
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - 'apt-mirror'
  notify: 'systemctl start apt-mirror.service'
